from pathlib import Path
import subprocess
stories={
'noah':'''Uma arca cheia de amor. Uma história inspirada no livro de Gênesis. Olá, pequeno coração. Hoje vamos conhecer Noé. Noé amava a Deus e cuidava do mundo ao seu redor. Um dia, Deus pediu que ele construísse uma arca. Era um barco muito, muito grande. Toc, toc, toc. Com paciência, Noé foi trabalhando. E então, chegaram os animais. Dois elefantes, com passos pesados. Duas girafas, com pescoços compridos. E passarinhos, cantando pelo caminho. Dentro da arca, havia um lugar para cada um. Quando a chuva chegou, Noé e sua família cuidaram dos animais. Havia comida, companhia e carinho. Os dias passaram. Até que uma pombinha voltou com uma folhinha verde no bico. A terra estava aparecendo de novo! Quando todos saíram, o céu ganhou um lindo arco-íris. Era o sinal da promessa de Deus. Noé sorriu. E nós também podemos aprender a cuidar. De um bichinho. De uma plantinha. De alguém que precisa de amor. Cada pequeno cuidado faz o mundo florescer. Esta foi uma narração demonstrativa da Sementinha. Até a próxima história.''',
'david':'''Pequeno pastor, grande coração. Uma história inspirada na infância de Davi e no Salmo vinte e três. Lá nas colinas de Belém, vivia um menino chamado Davi. Ele cuidava das ovelhas de sua família. Toda manhã, Davi levava o rebanho para encontrar capim fresquinho e água tranquila. Ele conhecia cada ovelhinha. A que gostava de correr. A que andava bem devagar. E a que sempre queria ficar pertinho. Enquanto elas descansavam, Davi tocava sua harpa e cantava para Deus. Às vezes, o caminho parecia difícil. Mas Davi lembrava que não estava sozinho. Assim como ele cuidava de suas ovelhas, Deus cuidava dele. O Senhor é o meu pastor, nada me faltará. Que pensamento bonito! Você também pode cuidar de alguém hoje. Pode ajudar um amigo, repartir um brinquedo, ou oferecer um abraço. Não é preciso ser grande para ter um coração cheio de amor. Agora, pense em uma pessoa de quem você gosta. Que tal fazer uma pequena gentileza para ela? Esta foi uma narração demonstrativa da Sementinha. Até a próxima história.''',
'night':'''Paz no barquinho. Uma história tranquila inspirada no evangelho de Marcos. Encontre uma posição bem gostosa. Solte os ombros. Respire devagar. Imagine um barquinho sobre um lago. A água balança suavemente. Para lá. E para cá. Jesus e seus amigos estão juntos. Depois de um dia cheio de encontros, Jesus descansa. Um vento forte começa a soprar. Os amigos sentem medo e chamam por ele. Jesus se levanta. E pede ao vento e ao mar que se acalmem. Aos poucos, tudo fica tranquilo. O vento descansa. A água se aquieta. Os amigos percebem que Jesus está ali. Quando sentir medo, você pode conversar com alguém que cuida de você. E pode fazer uma oração. Jesus, obrigado por este dia. Obrigado pelas pessoas que me amam. Cuida do meu coração enquanto eu descanso. Amém. Agora o barquinho segue bem devagar. A noite está quietinha. Você pode fechar os olhos. O dia terminou. E o amor de Deus continua com você. Boa noite, pequeno coração. Esta foi uma narração demonstrativa da Sementinha.'''
}
for name,text in stories.items():
 p=Path('/tmp')/f'sementinha-{name}.txt';p.write_text(text)
 subprocess.run(['say','-v','Luciana','-r','145','-f',str(p),'-o',f'/tmp/sementinha-{name}.aiff'],check=True)
 subprocess.run(['ffmpeg','-y','-loglevel','error','-i',f'/tmp/sementinha-{name}.aiff','-c:a','aac','-b:a','96k',f'dist/assets/{name}.m4a'],check=True)
